### ISSUE TITLE
App looses access to recovery

### ISSUE THREAD

**Issue by auguster** [Tasssadar/MultiROMMgr#52]
I used your wonderful app on my Nexus 5 Android L preview. Everything was working fine, multibooting into Ubuntu Touch and Kali Nethunter. Though I had twice the problem of the app saying that the "revovery is not installed ...". I couldn't figure out how to fix it: inject cur. boot img, re-flash Multirom TWRP, fix permissions and so on didn't fix it.

Un-installing the app and re-installing it nailed it. So there is probably something wrong with the data the app stores. If it occurs again, I'll let you know if clearing the app cache or deleting the app's data fixes it.

**Comment by RokeJulianLockhart** [comment]
@auguster, did it occur subsequently?

**Comment by auguster** [comment]
I honestly don't recall, that was 8 years ago and I've changed phone...
