### ISSUE TITLE
Add the ability to flash zips to secondary ROMs 

### ISSUE THREAD

**Issue by Zer0t3ch** [Tasssadar/MultiROMMgr#76]
Naturally, you shouldn't be able to flash the currently-running ROM, but flashing the others, even from inside android, should be possible.

**Comment by Tasssadar** [comment]
I have to disagree, flashing ZIPs from inside of Android should never be possible. Recovery is some kind of known environment the ZIP can make changes in while running Android most definitely is not.

**Comment by Zer0t3ch** [comment]
I thought recovery was just a version of Android?

**Comment by Tasssadar** [comment]
it's completely separate operating system

**Comment by Zer0t3ch** [comment]
@Tasssadar Sorry, didn't realize that. I thought OpenRecovery scripts were just shell scripts that any Android/Linux could execute.
