### ISSUE TITLE
Add support for Oneplus One (A1001)

### ISSUE THREAD

**Issue by Jamesits** [Tasssadar/MultiROMMgr#81]
A1001 is China Unicom version of Oneplue One, and have exactly the same hardware (except that model number), and any ROMs for A0001 works on A1001 too. However in MultiROM Manager this model is shown as unsupported. Would you please add support for A1001? Thanks.

**Comment by MorcCrafak** [comment]
Try go in settings click on version . after developer settings unlocked click oo rename this device and type A1000.this should work.
